apiVersion: v1
kind: ServiceAccount
metadata:
  name: duckdb-analysis-sa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: duckdb-analysis-sa@infrastructure-433717.iam.gserviceaccount.com
